from selenium import webdriver
from selenium.webdriver.common.by import By
import time
import unittest

class TestLoginSuccess(unittest.TestCase):
    driver = webdriver.Chrome()
    driver.get("https://www.saucedemo.com/")
    elem = driver.find_element(By.NAME, "user-name")
    elem.send_keys("standard_user")
    elem = driver.find_element(By.NAME, "password")
    elem.send_keys("secret_sauce")
    elem = driver.find_element(By.ID, "login-button").click()
    time.sleep(5)

class TestLoginFailedUsername(unittest.TestCase):
    drive = webdriver.Chrome()
    drive.get("https://www.saucedemo.com/")
    elem = drive.find_element(By.NAME, "user-name")
    elem.send_keys("maulid_wifa")
    elem = drive.find_element(By.ID, "password")
    elem.send_keys("secret_sauce")
    drive.find_element(By.ID, "login-button").click()
    time.sleep(2)
   
class TestLoginFailedPassword(unittest.TestCase):
    drive = webdriver.Chrome()
    drive.get("https://www.saucedemo.com/")
    elem = drive.find_element(By.ID, "user-name")
    elem.send_keys("standard_user")
    elem = drive.find_element(By.ID, "password")
    elem.send_keys("maulidwifa")
    elem = drive.find_element(By.ID, "login-button").click()
    time.sleep(2)
   
class TestCaseAddBelanja(unittest.TestCase):
    driver = webdriver.Chrome()
    driver.get("https://www.saucedemo.com")
    elem = driver.find_element(By.NAME, "user-name")
    elem.send_keys("standard_user")
    elem = driver.find_element(By.NAME, "password")
    elem.send_keys("secret_sauce")
    elem = driver.find_element(By.ID, "login-button").click()
    time.sleep(2)
    elem = driver.find_element(By.ID, "add-to-cart-sauce-labs-backpack").click()
    time.sleep(3)
    elem = driver.find_element(By.ID, "add-to-cart-sauce-labs-bike-light").click()
    time.sleep(3)
    elem = driver.find_element(By.ID, "add-to-cart-sauce-labs-bolt-t-shirt").click()
    time.sleep(3)
    elem = driver.find_element(By.ID, "add-to-cart-sauce-labs-fleece-jacket").click()
    time.sleep(3)

class TestCaseBelanja(unittest.TestCase):
    driver = webdriver.Chrome()
    driver.get("https://www.saucedemo.com")
    elem = driver.find_element(By.NAME, "user-name")
    elem.send_keys("standard_user")
    elem = driver.find_element(By.NAME, "password")
    elem.send_keys("secret_sauce")
    elem = driver.find_element(By.ID, "login-button").click()
    time.sleep(5)
    elem = driver.find_element(By.ID, "add-to-cart-sauce-labs-backpack").click()
    time.sleep(3)
    elem = driver.find_element(By.ID, "shopping_cart_container").click()
    time.sleep(3)
    elem = driver.find_element(By.ID, "checkout").click()
    time.sleep(3)
    elem = driver.find_element(By.NAME, "firstName")
    elem.send_keys("Maulidwifa")
    time.sleep(3)
    elem = driver.find_element(By.NAME, "lastName")
    elem.send_keys("Fairuz")
    time.sleep(3)
    elem = driver.find_element(By.NAME, "postalCode")
    elem.send_keys("Sauce-Backpack")
    time.sleep(3)
    elem = driver.find_element(By.ID, "continue").click()
    time.sleep(3)
    elem = driver.find_element(By.ID, "finish").click()
    time.sleep(3)

class TestCaseProductSort(unittest.TestCase):
    driver = webdriver.Chrome()
    driver.get("https://www.saucedemo.com")
    elem = driver.find_element(By.NAME, "user-name")
    elem.send_keys("standard_user")
    elem = driver.find_element(By.NAME, "password")
    elem.send_keys("secret_sauce")
    elem = driver.find_element(By.ID, "login-button").click()
    time.sleep(3)
    elem = driver.find_element(By.CSS_SELECTOR, ".product_sort_container > option:nth-child(2)").click()
    time.sleep(3)
    elem = driver.find_element(By.CSS_SELECTOR, ".product_sort_container > option:nth-child(3)").click()
    time.sleep(3)
    elem = driver.find_element(By.CSS_SELECTOR, ".product_sort_container > option:nth-child(4)").click()
    time.sleep(3)

class TestCaseMenuAbout(unittest.TestCase):
    driver = webdriver.Chrome()
    driver.get("https://www.saucedemo.com")
    elem = driver.find_element(By.NAME, "user-name")
    elem.send_keys("standard_user")
    elem = driver.find_element(By.NAME, "password")
    elem.send_keys("secret_sauce")
    elem = driver.find_element(By.ID, "login-button").click()
    time.sleep(3)
    elem = driver.find_element(By.ID, "react-burger-menu-btn").click()
    time.sleep(3)
    elem = driver.find_element(By.ID, "about_sidebar_link").click()

class TestCaseLogout(unittest.TestCase):
    driver = webdriver.Chrome()
    driver.get("https://www.saucedemo.com")
    elem = driver.find_element(By.NAME, "user-name")
    elem.send_keys("standard_user")
    elem = driver.find_element(By.NAME, "password")
    elem.send_keys("secret_sauce")
    elem = driver.find_element(By.ID, "login-button").click()
    time.sleep(3)
    elem = driver.find_element(By.ID, "react-burger-menu-btn").click()
    time.sleep(3)
    elem = driver.find_element(By.ID, "logout_sidebar_link").click()
    time.sleep(3)